language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: sizlRqnbarBgzq1NeybZ2g6Pu+rJKAQ4bFmn2WRmxd/D/GuH2TLK9ciT24+2HYZCpcxjRiwdqRqbQ1OAztZd70CFsAmlH57/udqVyjE29rBEmER69rIbrybymcXNljpQ59k77xes0mgZxlHJPNA33JDls2Mqb+bjbY5CkPiEGu4jTxQ8C3swGQrQ3ezyuOCUuitZqRRCCrBNquzBm+0V6SbpBeX8X9VURBuxWVKmBg0mmq0AkYBH1/xVYk0zlOLBsXw+H5opAs4pUXDxkJs2Gb6gLOkbxXSmJSrokMkfvmsj62PfuhsPeV9SPowIOXko2A7b4XLOt6g2aiu2rYz6fpPz6Ci0euiYgwIKEgXkCdbGPQK2noI/9Rmz8X3sfU48rePzSW19M0yzXH9dcuR5fUYTIE5u7lb4mQDoaLTrOgK6mCNi/+1zg0wRa/vTzaxnUWDSyq8u/Dc8kVUYMlTbHV9jk1DR1mSU+DUF7NuSQy21it6rcTOSWPhb1z+LwGXgaNxpqJsDFcuaSUGSqx0k/fasgi4PeQkoObEhnG90w3/8DTQeO2EFqn11oviuDrditKNACscfWrT9UgmuJU5gDeXOpcugGnR6DBA+suE1q1qbdi24LYcpDptYkM5UXd4q0on1OzQSyVf+GUbKYWC5EcUYOPiTzhbx3TEF95GrPSs=
  - secure: CFocxsE9R28mGbQfyn3DmJ/1he14tXBpauSAa8/wAQe1CEojp1YDGS1RF/R+Ev58HJPTYfu4ngyYqaeCT94zN9v79OeLehdGyrL2vqSrOn9ouq5kMJ+DtDoAbscvEgo7Yn1bLuQzbbk/DD9XwMCmiT6iXuIBAlyhOmIBFO4EpP4yDkJr9oVvJok6+IiYuseJZGe0m2VIsSQ/REUdxkhqO63kTplLlctiCGeljk5B7B6oBsBTzycaUcw3NZN7p74HSXvUNo7Wvf/XL8d0LRcj/FfbR/lf6YHw5v39Bb2JUoMtYcAvoMZnO59835seYGomRcSxuzJ3eTxVzfQBmmRy3ZnpCVFmgrtdxEc4cHC1pW6L9luR1PAypIOLnQ9mp0KE7S9yJoArjF3SZ8OlJAL7zk3lkll5udD6z/t+9DNBBQapuEXys63FHC3v/CwtCcnhLBv+Yjfrtfig9fFLI8X0P5ciTVKxMNaUqBx1CGjY9ohL+vfvILD/NOFDFPKoQvphR+S0ohnAaOamMwfpb2u0A5Zd0jFvkawpcZgqbIoIX0ldGqVsFEkcFuhfCZkFTver6/1zpvc835+jCFjUTVUywMlVN3u3n2c4Z+wSaoxWo+dtjtEnFljEJL8X42AafQPI/65tB7FEW/dzpnRDUnHzgzocvkP8+Au7yn886l7qo2k=
